#!/usr/bin/python3
import os

"""
Arguments needed:
    - duck2spark:
        - input file / -i
        - output file / -o
        - loop count / -l
        - delay before run / -f
        - delay between loop runs / -r
        - Dont blink LED after execution / -n
    - USB-rubber-ducky-encoder:
        - input file / -i
        - output file / -o
        - keyboard layout / -l

    command to run: java -jar /opt/USB-Rubber-Ducky/Encoder/encoder.jar -i /mnt/files/dev/rubberDucky/test/test.duck -o raw.bin -l no && python2 /opt/duck2spark/duck2spark.py -i raw.bin -o sketch.ino && rm raw.bin
"""


def main():
    

if __name__ == "__main__":
    main()