#!/usr/bin/python3
import os

"""
Arguments needed:
    - duck2spark:
        - input file / -i
        - output file / -o
        - loop count / -l
        - delay before run / -f
        - delay between loop runs / -r
        - Dont blink LED after execution / -n
    - USB-rubber-ducky-encoder:
        - input file / -i
        - output file / -o
        - keyboard layout / -l
"""

def encode(lang, inputFile, outputFile):
    return


def main():
    print(os.system('pwd'))

if __name__ == "__main__":
    main()